### ISSUE TITLE
Odos integration

### ISSUE THREAD

**Issue by alexnorell** [0xdapper/aave-unwind#1]
Hey! I love that we're integrated here. Just a note, you don't need to make the `quote` and `assemble` endpoints if you aren't going to conditionally assemble. The `swap` endpoint does it all in one.

Full swagger docs page is available at https://api.odos.xyz

**Comment by 0xdapper** [comment]
Interesting, I couldn't find any docs for the API so I just mimicked whatever I saw happen on the website 😅 . Can you explain a little more on what is the difference between quote-and-assemble vs swap? Since I believe the path is locked in with the `pathId` passed on to the assemble request?

**Comment by alexnorell** [comment]
They are exactly the same, but it saves a round trip HTTP transaction.

Ideally, you would only call assemble if you were going to actually use the quote we provide. So if you want to rewrite it to do that, that would also work. 😄
